import { model } from "@medusajs/framework/utils"
import Conversation from "./conversation"

const Message = model.define("message", {
  id: model.id().primaryKey(),
  sender_type: model.enum(["customer", "vendor"]),
  sender_id: model.text(),
  content: model.text(),
  type: model
    .enum([
      "text",
      "image",
      "file",
      "audio",
      "product",
      "offer",
      "coupon",
      "order_update",
      "flash_sale",
      "video",
      "system",
    ])
    .default("text"),
  file_url: model.text().nullable(),
  // Données structurées des messages riches (product, offer, coupon, …)
  metadata: model.json().nullable(),
  is_read: model.boolean().default(false),
  delivered_at: model.dateTime().nullable(),
  // Réponse-citation : id du message cité
  reply_to_id: model.text().nullable(),
  // { [emoji]: ["customer:cus_123", "vendor:ven_456"] }
  reactions: model.json().nullable(),
  // conversation_id is auto-generated by belongsTo
  conversation: model.belongsTo(() => Conversation, { mappedBy: "messages" }),
})

export default Message
