import { model } from "@medusajs/framework/utils"
import Conversation from "./conversation"

const Message = model.define("message", {
  id: model.id().primaryKey(),
  sender_type: model.enum(["customer", "vendor"]),
  sender_id: model.text(),
  content: model.text(),
  type: model.enum(["text", "image", "file"]).default("text"),
  file_url: model.text().nullable(),
  is_read: model.boolean().default(false),
  // conversation_id is auto-generated by belongsTo
  conversation: model.belongsTo(() => Conversation, { mappedBy: "messages" }),
})

export default Message
